### ISSUE TITLE
Add akash deployment yml

### ISSUE THREAD

**Issue by hanshq** [CafeValidator/nodemonitor#1]
Hi, after some time i made this hostable on akash. This was my deploy.yml:

The system requirements can be lowered most likely.
```

---
version: "2.0"

services:
  pg-0:
    image: postgres:13
    env:
      - POSTGRES_USER=someUser
      - POSTGRES_PASSWORD=somePassword
      - POSTGRES_DB=zabbix
    expose:
      - port: 5432
        to:
          - service: zabbix
          - service: web
  zabbix:
    image: zabbix/zabbix-server-pgsql:ubuntu-5.0.6
    env:
      - DB_SERVER_HOST=pg-0
      - POSTGRES_USER=someUser
      - POSTGRES_PASSWORD=somePassword
      - POSTGRES_DB=zabbix
    expose:
      - port: 10051
        as: 10051
        to:
          - service: web
      - port: 10050
        as: 10050
        to:
          - service: web
    depends_on: 
      - service: pg-0
  web:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-5.0.6
    env:
      - DB_SERVER_HOST=pg-0 
      - POSTGRES_USER=someUser
      - POSTGRES_PASSWORD=somePassword
      - ZBX_SERVER_HOST=zabbix
      - POSTGRES_DB=zabbix
      - PHP_TZ=Europe/Berlin
    expose:
      - port: 8080
        as: 8080
        to:
          - global: true
    depends_on: 
      - service: zabbix
      - service: pg-0
profiles:
  compute:
    pg-0:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 256Mi
        storage:
          size: 1Gi
    zabbix:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          size: 512Mi
    web:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          size: 512Mi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        pg-0:
          denom: uakt
          amount: 100
        zabbix:
          denom: uakt
          amount: 100
        web:
          denom: uakt
          amount: 100

deployment:
  pg-0:
    dcloud:
      profile: pg-0
      count: 1
  zabbix:
    dcloud:
      profile: zabbix
      count: 1
  web:
    dcloud:
      profile: web
      count: 1

```
